export const FETCH_ROUTE_STOPS_START = "FETCH_ROUTE_STOPS_START"
export const FETCH_ROUTE_STOPS_SUCCESS = "FETCH_ROUTE_STOPS_SUCCESS"
export const STOP_LOADER = "STOP_LOADER"
export const CLEAR_STATE = "CLEAR_STATE"